/// Autogenerated file. Run the obfuscation command for refresh:
/// 
///      flutter pub run stringcare:obfuscate
/// 

// ignore_for_file: non_constant_identifier_names
class _Assets {
  _Assets();

  final String images_voyager_jpeg = "assets/images/voyager.jpeg";

}

class _Strings {
  _Strings();

  final String hello_there = "hello_there";
	final String hello_format = "hello_format";

}

class R {
  static _Assets assets = _Assets();
  static _Strings strings = _Strings();
}
  