/// Autogenerated file. Run the obfuscation command for refresh:
/// 
///      flutter pub run stringcare:obfuscate
/// 

// ignore_for_file: non_constant_identifier_names
class Assets {
  Assets();

  final String images_coding_svg = 'assets/images/coding.svg';
	final String images_voyager_jpeg = 'assets/images/voyager.jpeg';

}

class Strings {
  Strings();

  final String hello_there = 'hello_there';
	final String hello_format = 'hello_format';

}

class R {
  static Assets assets = Assets();
  static Strings strings = Strings();
}
  