/// Autogenerated file. Run the obfuscation command for refresh:
/// 
///      flutter pub run stringcare:obfuscate
/// 

class Assets {
  Assets();

  String images_voyager_jpeg = "assets/images/voyager.jpeg";

}

class Strings {
  Strings();

  String hello_there = "hello_there";
	String hello_format = "hello_format";

}

class R {
  static Assets assets = Assets();
  static Strings string = Strings();
}
  